### ISSUE TITLE
Tests abort if `./var/` does not exist

### ISSUE THREAD

**Issue by m0n0chr0m3** [luminescent-dreams/emseries#7]
# First symptom
When cloning the repo as-is, and running the tests, the tests fail since the directory `./var/` does not exist. Worse, the tests do not fail cleanly (e.g., with the error message that `Series::open` generates when `OpenOptions::open` fails [here](https://github.com/luminescent-dreams/emseries/blob/sol/src/series.rs#L38)), but simply trap/abort.

# Likely cause
As far as I can see, the reason is that the approach with the `SeriesFileCleanup` type is unsound: in each test in `series.rs`, a `SeriesFileCleanup` is set up regardless of whether `Series::open` will succeed. When `Series::open` fails, the call to `expect` gives rise to a panic, which unwinds the stack. This causes `SeriesFileCleanup::drop` to be called, which in turn [tries to `fs::remove_file`](https://github.com/luminescent-dreams/emseries/blob/sol/src/series.rs#L239) of the JSON-file in `./var/`, which still does not exist. Thus, the `expect` in the `SeriesFileCleanup::drop` is invoked, aborting the program immediately.

# Solution/Workarounds
A first workaround targets only the initial symptom: add a `./var/` to the repo. This does not solve the bigger problem, but without that, the tests will still fail — albeit in an easily addressable way.

Second, solving the actual problem doesn't look very easy, as the filesystem operations are inherently race'y. I think that the cleanest option is to allow the `fs::remove_file` to fail silently, or at least to silently ignore failures of the type `std::io::error::ErrorKind::NotFound`. The `SeriesFileCleanup` _did_ achieve its goal if the file is gone, after all. What's your view on this situation?

**Comment by savannidgerinel** [comment]
I'll have to think about it for a while, but at first glance I think you are correct and that cleaning up the file should fail silently, or it should print a warning. I'll evaluate this in more detail after work.

**Comment by savannidgerinel** [comment]
The tempfile module has multiple methods that help out with all of this. Including that likely removes all of the need to do this fallable test setup.
